---
title: "GSE152418"
author: "Arun Kumar"
date: "2025-05-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(TCGAbiolinks)
library(tidyverse)
library(maftools)
library(pheatmap)
library(SummarizedExperiment)
library(edgeR)
library(limma)
library(GEOquery)
library(tidyverse)
library(DESeq2)
library(patchwork)
library(CorLevelPlot)

```


```{r}
Sys.setenv(XML_CONFIG = "/usr/bin/xml2-config")
#install.packages("XML", type = "source")
```

```{r}
# 1. Fetch Data 

GSEdata <- read_table("data/GSE152418_p20047_Study1_RawCounts.txt")    
GSEdata
```


```{r}
geo_id <- "GSE152418"
gse <- getGEO(geo_id, GSEMatrix = TRUE)
phenoData <- pData(phenoData(gse[[1]]))
head(phenoData)
phenoData <- phenoData[,c(1,2,46:50)]
```

```{r}
# prepare data
GSEdata[1:10,1:10]

GSEdata <- GSEdata %>% 
  gather(key = 'samples', value = 'counts', -ENSEMBLID) %>% 
  mutate(samples = gsub('\\.', '-', samples)) %>% 
  inner_join(., phenoData, by = c('samples' = 'title')) %>% 
  dplyr::select(1,3,4) %>% 
  spread(key = 'geo_accession', value = 'counts') %>% 
  column_to_rownames(var = 'ENSEMBLID')

GSEdata
```


```{r}
gsg <- goodSamplesGenes(t(GSEdata))
```
```{r}
summary(gsg)
```


```{r}
GSEdata <- GSEdata[gsg$goodGenes == TRUE,]

```

```{r}
htree <- hclust(dist(t(GSEdata)),method = "average")
plot(htree)
```

```{r}
# exclude outlier samples
samples.to.be.excluded <- c('GSM4615000', 'GSM4614993', 'GSM4614995')
GSEdata.subset <- GSEdata[,!(colnames(GSEdata) %in% samples.to.be.excluded)]
```

```{r}
colData <- phenoData %>% 
  filter(!row.names(phenoData) %in% samples.to.be.excluded)

# fixing column names in colData
names(colData)
names(colData) <- gsub(':ch1', '', names(colData))
names(colData) <- gsub('\\s', '_', names(colData))

names(colData)
```

```{r}
all(rownames(colData) %in% colnames(GSEdata.subset))
all(rownames(colData) == colnames(GSEdata.subset))
```

```{r}
# create dds
dds <- DESeqDataSetFromMatrix(countData = GSEdata.subset,
                              colData = colData,
                              design = ~ 1) # not spcifying model
```
```{r}
## remove all genes with counts < 15 in more than 75% of samples (31*0.75=23.25)
## suggested by WGCNA on RNAseq FAQ

dds75 <- dds[rowSums(counts(dds) >= 15) >= 24,]
nrow(dds75)
```

```{r}
# perform variance stabilization
dds_norm <- vst(dds75)

```

```{r}
# get normalized counts
norm.counts <- assay(dds_norm) %>% 
  t()
```


```{r}
# 4. Network Construction  
# Choose a set of soft-thresholding powers
power <- c(c(1:10), seq(from = 12, to = 50, by = 2))
power
```

```{r}
# Call the network topology analysis function
sft <- pickSoftThreshold(norm.counts,
                  powerVector = power,
                  networkType = "signed",
                  verbose = 5)

sft.data <- sft$fitIndices
```


```{r}
# visualization to pick power

a1 <- ggplot(sft.data, aes(Power, SFT.R.sq, label = Power)) +
  geom_point() +
  geom_text(nudge_y = 0.1) +
  geom_hline(yintercept = 0.8, color = 'red') +
  labs(x = 'Power', y = 'Scale free topology model fit, signed R^2') +
  theme_classic()


a2 <- ggplot(sft.data, aes(Power, mean.k., label = Power)) +
  geom_point() +
  geom_text(nudge_y = 0.1) +
  labs(x = 'Power', y = 'Mean Connectivity') +
  theme_classic()
```


```{r}
a1+a2
```

```{r}
# convert matrix to numeric
norm.counts[] <- sapply(norm.counts, as.numeric)

soft_power <- 18
temp_cor <- cor
cor <- WGCNA::cor
```


```{r}
# memory estimate w.r.t blocksize
bwnet <- blockwiseModules(norm.counts,
                 maxBlockSize = 14000,
                 TOMType = "signed",
                 power = soft_power,
                 mergeCutHeight = 0.25,
                 numericLabels = FALSE,
                 randomSeed = 1234,
                 verbose = 3)
```
```{r}
cor <- temp_cor
```


```{r}
# 5. Module Eigengenes 
module_eigengenes <- bwnet$MEs
head(module_eigengenes)
table(bwnet$colors)

```

```{r}
# Plot the dendrogram and the module colors before and after merging underneath
plotDendroAndColors(bwnet$dendrograms[[1]], cbind(bwnet$unmergedColors, bwnet$colors),
                    c("unmerged", "merged"),
                    dendroLabels = FALSE,
                    addGuide = TRUE,
                    hang= 0.03,
                    guideHang = 0.05)
```

```{r}
# create traits file - binarize categorical variables
traits <- colData %>% 
  mutate(disease_state_bin = ifelse(grepl('COVID', disease_state), 1, 0)) %>% 
  dplyr::select(8)
traits
```


```{r}
# binarize categorical variables

colData$severity <- factor(colData$severity, 
                           levels = c("Healthy", "Convalescent", 
                                      "ICU", "Moderate", "Severe"))


severity.out <- binarizeCategoricalColumns(colData$severity,
                           includePairwise = FALSE,
                           includeLevelVsAll = TRUE,
                           minCount = 1)
```

```{r}
traits <- cbind(traits,severity.out)
```


```{r}
# Define numbers of genes and samples
nSamples <- nrow(norm.counts)
nGenes <- ncol(norm.counts)
nSamples
nGenes
```


```{r}
module.trait.corr <- cor(module_eigengenes, traits, use = 'p')
module.trait.corr.pvals <- corPvalueStudent(module.trait.corr, nSamples)
```

```{r}
# visualize module-trait association as a heatmap

heatmap.data <- merge(module_eigengenes, traits, by = 'row.names')

head(heatmap.data)
```

```{r}
CorLevelPlot(heatmap.data,
             x = names(heatmap.data)[19:23],
             y = names(heatmap.data)[1:18],
             col = c("blue1", "skyblue", "white", "pink", "red"))
```


```{r}
module.gene.mapping <- as.data.frame(bwnet$colors)

```

```{r}
module.gene.mapping %>% 
  filter(`bwnet$colors` == 'turquoise') %>% 
  rownames()
```

































































































