---
title: "Untitled"
author: "Arun Kumar"
date: "2025-06-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(time = TRUE)
```

```{r}
#renv::deactivate()
unlink("renv/library", recursive = TRUE)
renv::activate()
renv::restore()

```

```{r}
# Define the file path to the plots directory
plots_dir <- "plots"

# Create the plots folder if it doesn't exist
if (!dir.exists(plots_dir)) {
  dir.create(plots_dir)
}

# Define the file path to the results directory
results_dir <- "results"

# Create the results folder if it doesn't exist
if (!dir.exists(results_dir)) {
  dir.create(results_dir)
}
```


```{r}
# Define the file path to the data directory
# Replace with the path of the folder the files will be in
data_dir <- file.path("data", "SRP140558")

# Declare the file path to the gene expression matrix file
# inside directory saved as `data_dir`
# Replace with the path to your dataset file
data_file <- file.path(data_dir, "SRP140558.tsv")

# Declare the file path to the metadata file
# inside the directory saved as `data_dir`
# Replace with the path to your metadata file
metadata_file <- file.path(data_dir, "metadata_SRP140558.tsv")
```


```{r}
# Check if the gene expression matrix file is at the path stored in `data_file`
file.exists(data_file)

# Check if the metadata file is at the file path stored in `metadata_file`
file.exists(metadata_file)
```

```{r}
library(tidyverse)
library(devtools)
library(TCGAbiolinks)
library(DESeq2)
library(WGCNA)
library(impute)
library(limma)
library(ggforce)
library(complexHeatmap)
```

```{r}
# Read in metadata TSV file
metadata <- readr::read_tsv(metadata_file)
head(metadata)

# Read in data TSV file
df <- readr::read_tsv(data_file) %>%
  # Here we are going to store the gene IDs as row names so that we can have a numeric matrix to perform calculations on later
  tibble::column_to_rownames("Gene")
head(df)
```

```{r}
# Make the data in the order of the metadata
df <- df %>%
  dplyr::select(metadata$refinebio_accession_code)

# Check if this is in the same order
all.equal(colnames(df), metadata$refinebio_accession_code)
```
```{r}
df <- round(df) %>% 
  as.data.frame() %>% 
   dplyr::filter(rowSums(.) >= 50)
head(df)
```

```{r}
metadata <- metadata %>%
  dplyr::mutate(
    time_point = dplyr::case_when(
      # Create our new variable based on refinebio_title containing AV/CV
      stringr::str_detect(refinebio_title, "_AV_") ~ "acute illness",
      stringr::str_detect(refinebio_title, "_CV_") ~ "recovering"
    ),
    # It's easier for future items if this is already set up as a factor
    time_point = as.factor(time_point)
    
  )
head(metadata)
```

```{r}
# Create a `DESeqDataSet` object
dds <- DESeqDataSetFromMatrix(
  countData = df, # Our prepped data frame with counts
  colData = metadata, # Data frame with annotation for our samples
  design = ~1 # Here we are not specifying a model
)
```

```{r}
dds_norm <- vst(dds)
dds_norm
```

```{r}
normalized_counts <- t(assay(dds_norm))
#normalized_counts
nrow(normalized_counts)
ncol(normalized_counts)
```

```{r}
power <-  c(c(1:10), seq(from = 12, to = 50, by = 2))
power
```

```{r}
#stf <-  pickSoftThreshold(normalized_counts,
                        #  powerVector = power,
                        #  networkType = "signed",
                        #  verbose = 5)

sft <- pickSoftThreshold(normalized_counts,
  dataIsExpr = TRUE,
  corFnc = cor,
  networkType = "signed"
)
stf_data <- stf$fitIndices
```

```{r}
# visualization to pick power
a1 <- ggplot(stf_data, aes(Power, SFT.R.sq, label = Power)) +
  geom_point() +
  geom_text(nudge_y = 0.1) +
  geom_hline(yintercept = 0.8, color = 'red') +
  labs(x = 'Power', y = 'Scale free topology model fit, signed R^2') +
  theme_classic()

a2 <- ggplot(stf_data, aes(Power, mean.k., label = Power)) +
  geom_point() +
  geom_text(nudge_y = 0.1) +
  labs(x = 'Power', y = 'Mean Connectivity') +
  theme_classic()
a1+a2
```

```{r}
normalized_counts[] <-  sapply(normalized_counts, as.numeric)
soft_power <- 7
temp_cor <-  cor
cor <- WGCNA::cor
```


```{r}
# memory estimate w.r.t blocksize
bwnet = blockwiseModules(normalized_counts,
                         maxBlockSize = ncol(normalized_counts),
                         TOMType = "signed", 
                         power = soft_power,
                         mergeCutHeight = 0.25,
                         numericLabels = FALSE, 
                         randomSeed = 1234,
                         verbose = 3)

```

```{r}
# Number of genes in block 1
length(bwnet$blockGenes[[1]])
length(bwnet$unmergedColors)
length(bwnet$colors)


```

```{r}
plotDendroAndColors(bwnet$dendrograms[[1]],
                    cbind(bwnet$unmergedColors,
                          bwnet$colors),
                    c("unmerged","merged"),
                    dendroLabels = FALSE,
                    hang = 0.03,
                    guideHang = 0.05)
```

```{r}
module_eigengenes <- bwnet$MEs

# Print out a preview
head(module_eigengenes)
```


```{r}
all.equal(metadata$refinebio_accession_code, rownames(module_eigengenes))
```

```{r}
# Create the design matrix from the `time_point` variable
des_mat <- model.matrix(~ metadata$time_point)
```

```{r}
# lmFit() needs a transposed version of the matrix
fit <- limma::lmFit(t(module_eigengenes), design = des_mat)

# Apply empirical Bayes to smooth standard errors
fit <- limma::eBayes(fit)
```


```{r}
# Apply multiple testing correction and obtain stats
stats_df <- limma::topTable(fit, number = ncol(module_eigengenes)) %>%
  tibble::rownames_to_column("module")
```

```{r}
module_19_df <- module_eigengenes %>%
  tibble::rownames_to_column("accession_code") %>%
  # Here we are performing an inner join with a subset of metadata
  dplyr::inner_join(metadata %>%
    dplyr::select(refinebio_accession_code, time_point),
  by = c("accession_code" = "refinebio_accession_code")
  )
```


```{r}
ggplot(
  module_19_df,
  aes(
    x = time_point,
    y = MEyellow,
    color = time_point
  )
) +
  # a boxplot with outlier points hidden (they will be in the sina plot)
  geom_boxplot(width = 0.2, outlier.shape = NA) +
  # A sina plot to show all of the individual data points
  ggforce::geom_sina(maxwidth = 0.3) +
  theme_classic()
```

```{r}
gene_module_key <- tibble::enframe(bwnet$colors, name = "gene", value = "module") %>%
  # Let's add the `ME` part so its more clear what these numbers are and it matches elsewhere
  dplyr::mutate(module = paste0("ME", module))
```

```{r}
gene_module_key %>%
  dplyr::filter(module == "MEyellow")
```


```{r}
make_module_heatmap <- function(module_name,
                                expression_mat = normalized_counts,
                                metadata_df = metadata,
                                gene_module_key_df = gene_module_key,
                                module_eigengenes_df = module_eigengenes) {
  # Create a summary heatmap of a given module.
  #
  # Args:
  # module_name: a character indicating what module should be plotted, e.g. "ME19"
  # expression_mat: The full gene expression matrix. Default is `normalized_counts`.
  # metadata_df: a data frame with refinebio_accession_code and time_point
  #              as columns. Default is `metadata`.
  # gene_module_key: a data.frame indicating what genes are a part of what modules. Default is `gene_module_key`.
  # module_eigengenes: a sample x eigengene data.frame with samples as row names. Default is `module_eigengenes`.
  #
  # Returns:
  # A heatmap of expression matrix for a module's genes, with a barplot of the
  # eigengene expression for that module.

  # Set up the module eigengene with its refinebio_accession_code
  module_eigengene <- module_eigengenes_df %>%
    dplyr::select(all_of(module_name)) %>%
    tibble::rownames_to_column("refinebio_accession_code")

  # Set up column annotation from metadata
  col_annot_df <- metadata_df %>%
    # Only select the treatment and sample ID columns
    dplyr::select(refinebio_accession_code, time_point, refinebio_subject) %>%
    # Add on the eigengene expression by joining with sample IDs
    dplyr::inner_join(module_eigengene, by = "refinebio_accession_code") %>%
    # Arrange by patient and time point
    dplyr::arrange(time_point, refinebio_subject) %>%
    # Store sample
    tibble::column_to_rownames("refinebio_accession_code")

  # Create the ComplexHeatmap column annotation object
  col_annot <- ComplexHeatmap::HeatmapAnnotation(
    # Supply treatment labels
    time_point = col_annot_df$time_point,
    # Add annotation barplot
    module_eigengene = ComplexHeatmap::anno_barplot(dplyr::select(col_annot_df, module_name)),
    # Pick colors for each experimental group in time_point
    col = list(time_point = c("recovering" = "#f1a340", "acute illness" = "#998ec3"))
  )

  # Get a vector of the Ensembl gene IDs that correspond to this module
  module_genes <- gene_module_key_df %>%
    dplyr::filter(module == module_name) %>%
    dplyr::pull(gene)

  # Set up the gene expression data frame
  mod_mat <- expression_mat %>%
    t() %>%
    as.data.frame() %>%
    # Only keep genes from this module
    dplyr::filter(rownames(.) %in% module_genes) %>%
    # Order the samples to match col_annot_df
    dplyr::select(rownames(col_annot_df)) %>%
    # Data needs to be a matrix
    as.matrix()

  # Normalize the gene expression values
  mod_mat <- mod_mat %>%
    # Scale can work on matrices, but it does it by column so we will need to
    # transpose first
    t() %>%
    scale() %>%
    # And now we need to transpose back
    t()

  # Create a color function based on standardized scale
  color_func <- circlize::colorRamp2(
    c(-2, 0, 2),
    c("#67a9cf", "#f7f7f7", "#ef8a62")
  )

  # Plot on a heatmap
  heatmap <- ComplexHeatmap::Heatmap(mod_mat,
    name = module_name,
    # Supply color function
    col = color_func,
    # Supply column annotation
    bottom_annotation = col_annot,
    # We don't want to cluster samples
    cluster_columns = FALSE,
    # We don't need to show sample or gene labels
    show_row_names = FALSE,
    show_column_names = FALSE
  )

  # Return heatmap
  return(heatmap)
}
```


```{r}
mod_19_heatmap <- make_module_heatmap(module_name = "MEyellow")

# Print out the plot
mod_19_heatmap
```




























































































